// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const feedStats = `-- name: FeedStats :one
SELECT
    count(*)::int AS posts_total,
    (count(*) FILTER (WHERE is_ad))::int AS ads_hidden
FROM posts
WHERE published_at > $1::timestamptz
`

type FeedStatsRow struct {
	PostsTotal int32
	AdsHidden  int32
}

func (q *Queries) FeedStats(ctx context.Context, since pgtype.Timestamptz) (FeedStatsRow, error) {
	row := q.db.QueryRow(ctx, feedStats, since)
	var i FeedStatsRow
	err := row.Scan(&i.PostsTotal, &i.AdsHidden)
	return i, err
}

const listPublishedStories = `-- name: ListPublishedStories :many
SELECT
    s.id,
    s.topic,
    s.info_type,
    s.heaviness,
    s.title_neutral,
    s.summary,
    s.meaning,
    s.post_count,
    s.source_count,
    s.region_code,
    s.country,
    s.lang,
    s.updated_at,
    COALESCE((
        SELECT jsonb_agg(jsonb_build_object('title', src.title, 'url', fp.url) ORDER BY src.title)
        FROM (
            SELECT DISTINCT ON (p.source_id) p.source_id, p.url
            FROM posts p
            WHERE p.story_id = s.id
            ORDER BY p.source_id, p.published_at
        ) fp
        JOIN sources src ON src.id = fp.source_id
    ), '[]'::jsonb)::jsonb AS sources
FROM stories s
WHERE s.status = 'published' AND s.title_neutral IS NOT NULL AND s.summary IS NOT NULL
  AND s.topic IS NOT NULL AND s.info_type IS NOT NULL AND s.heaviness IS NOT NULL
  AND s.updated_at > $1::timestamptz
ORDER BY s.updated_at DESC, s.id DESC
`

type ListPublishedStoriesRow struct {
	ID           int64
	Topic        pgtype.Text
	InfoType     pgtype.Text
	Heaviness    pgtype.Text
	TitleNeutral pgtype.Text
	Summary      pgtype.Text
	Meaning      pgtype.Text
	PostCount    int32
	SourceCount  int32
	RegionCode   pgtype.Text
	Country      pgtype.Text
	Lang         string
	UpdatedAt    pgtype.Timestamptz
	Sources      []byte
}

// Опубликованные сюжеты за окно. Источники: по одной ссылке на источник (самый ранний пост).
func (q *Queries) ListPublishedStories(ctx context.Context, since pgtype.Timestamptz) ([]ListPublishedStoriesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedStories, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedStoriesRow
	for rows.Next() {
		var i ListPublishedStoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.InfoType,
			&i.Heaviness,
			&i.TitleNeutral,
			&i.Summary,
			&i.Meaning,
			&i.PostCount,
			&i.SourceCount,
			&i.RegionCode,
			&i.Country,
			&i.Lang,
			&i.UpdatedAt,
			&i.Sources,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
