// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: laws.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listVerifiedLaws = `-- name: ListVerifiedLaws :many
SELECT
    id, title, what_changed, who_affected, actions, audience_tags, region_code, status,
    introduced_at, passed_at, signed_at, effective_at,
    official_url, bill_url, act_number, verified_at
FROM law_changes
WHERE verified
  AND (effective_at IS NULL OR (effective_at >= $1::date AND effective_at <= $2::date))
ORDER BY effective_at NULLS LAST, id
`

type ListVerifiedLawsParams struct {
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

type ListVerifiedLawsRow struct {
	ID           int64
	Title        string
	WhatChanged  string
	WhoAffected  string
	Actions      []byte
	AudienceTags []string
	RegionCode   pgtype.Text
	Status       string
	IntroducedAt pgtype.Date
	PassedAt     pgtype.Date
	SignedAt     pgtype.Date
	EffectiveAt  pgtype.Date
	OfficialUrl  pgtype.Text
	BillUrl      pgtype.Text
	ActNumber    pgtype.Text
	VerifiedAt   pgtype.Timestamptz
}

// Только проверенные вручную. Законы без даты вступления в силу (внесены/приняты) попадают всегда.
func (q *Queries) ListVerifiedLaws(ctx context.Context, arg ListVerifiedLawsParams) ([]ListVerifiedLawsRow, error) {
	rows, err := q.db.Query(ctx, listVerifiedLaws, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerifiedLawsRow
	for rows.Next() {
		var i ListVerifiedLawsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.WhatChanged,
			&i.WhoAffected,
			&i.Actions,
			&i.AudienceTags,
			&i.RegionCode,
			&i.Status,
			&i.IntroducedAt,
			&i.PassedAt,
			&i.SignedAt,
			&i.EffectiveAt,
			&i.OfficialUrl,
			&i.BillUrl,
			&i.ActNumber,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
