// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: laws.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveRegionalTitles = `-- name: ApproveRegionalTitles :many
UPDATE law_changes SET verified = true, verified_at = now()
WHERE kind = 'regional_title' AND NOT verified AND NOT rejected
RETURNING region_code
`

// Массовое подтверждение региональных законов, у которых нет текста модели: только официальное название, дата и ссылка.
func (q *Queries) ApproveRegionalTitles(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, approveRegionalTitles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var region_code pgtype.Text
		if err := rows.Scan(&region_code); err != nil {
			return nil, err
		}
		items = append(items, region_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLaws = `-- name: CountLaws :one
SELECT
    count(*) FILTER (WHERE verified)                       AS verified,
    count(*) FILTER (WHERE NOT verified AND NOT rejected)  AS drafts,
    count(*) FILTER (WHERE rejected)                       AS rejected
FROM law_changes
`

type CountLawsRow struct {
	Verified int64
	Drafts   int64
	Rejected int64
}

func (q *Queries) CountLaws(ctx context.Context) (CountLawsRow, error) {
	row := q.db.QueryRow(ctx, countLaws)
	var i CountLawsRow
	err := row.Scan(&i.Verified, &i.Drafts, &i.Rejected)
	return i, err
}

const countRegionalDrafts = `-- name: CountRegionalDrafts :one
SELECT count(*)::int FROM law_changes WHERE kind = 'regional_title' AND NOT verified AND NOT rejected
`

func (q *Queries) CountRegionalDrafts(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countRegionalDrafts)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertLawDraft = `-- name: InsertLawDraft :one
INSERT INTO law_changes (
    eo_number, title, what_changed, who_affected, actions, audience_tags, region_code, status,
    passed_at, signed_at, effective_at, official_url, source_url, act_number, quotes, kind
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (eo_number) DO NOTHING
RETURNING id
`

type InsertLawDraftParams struct {
	EoNumber     pgtype.Text
	Title        string
	WhatChanged  string
	WhoAffected  string
	Actions      []byte
	AudienceTags []string
	RegionCode   pgtype.Text
	Status       string
	PassedAt     pgtype.Date
	SignedAt     pgtype.Date
	EffectiveAt  pgtype.Date
	OfficialUrl  pgtype.Text
	SourceUrl    pgtype.Text
	ActNumber    pgtype.Text
	Quotes       []byte
	Kind         string
}

func (q *Queries) InsertLawDraft(ctx context.Context, arg InsertLawDraftParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertLawDraft,
		arg.EoNumber,
		arg.Title,
		arg.WhatChanged,
		arg.WhoAffected,
		arg.Actions,
		arg.AudienceTags,
		arg.RegionCode,
		arg.Status,
		arg.PassedAt,
		arg.SignedAt,
		arg.EffectiveAt,
		arg.OfficialUrl,
		arg.SourceUrl,
		arg.ActNumber,
		arg.Quotes,
		arg.Kind,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRejectedLaw = `-- name: InsertRejectedLaw :exec
INSERT INTO law_changes (eo_number, title, what_changed, who_affected, status, signed_at, act_number, rejected, reject_reason)
VALUES ($1, $2, '', '', 'signed', $3, $4, true, $5)
ON CONFLICT (eo_number) DO NOTHING
`

type InsertRejectedLawParams struct {
	EoNumber     pgtype.Text
	Title        string
	SignedAt     pgtype.Date
	ActNumber    pgtype.Text
	RejectReason pgtype.Text
}

// Отклонённые сохраняются, чтобы не обрабатывать один и тот же закон повторно.
func (q *Queries) InsertRejectedLaw(ctx context.Context, arg InsertRejectedLawParams) error {
	_, err := q.db.Exec(ctx, insertRejectedLaw,
		arg.EoNumber,
		arg.Title,
		arg.SignedAt,
		arg.ActNumber,
		arg.RejectReason,
	)
	return err
}

const lawSeen = `-- name: LawSeen :one
SELECT EXISTS (SELECT 1 FROM law_changes WHERE eo_number = $1)
`

func (q *Queries) LawSeen(ctx context.Context, eoNumber pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, lawSeen, eoNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listLawDrafts = `-- name: ListLawDrafts :many
SELECT kind, id, eo_number, title, what_changed, who_affected, actions, audience_tags, region_code, status,
       passed_at, signed_at, effective_at, official_url, source_url, act_number, quotes
FROM law_changes
WHERE NOT verified AND NOT rejected AND kind = 'federal'
ORDER BY effective_at NULLS LAST, id
`

type ListLawDraftsRow struct {
	Kind         string
	ID           int64
	EoNumber     pgtype.Text
	Title        string
	WhatChanged  string
	WhoAffected  string
	Actions      []byte
	AudienceTags []string
	RegionCode   pgtype.Text
	Status       string
	PassedAt     pgtype.Date
	SignedAt     pgtype.Date
	EffectiveAt  pgtype.Date
	OfficialUrl  pgtype.Text
	SourceUrl    pgtype.Text
	ActNumber    pgtype.Text
	Quotes       []byte
}

func (q *Queries) ListLawDrafts(ctx context.Context) ([]ListLawDraftsRow, error) {
	rows, err := q.db.Query(ctx, listLawDrafts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLawDraftsRow
	for rows.Next() {
		var i ListLawDraftsRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.EoNumber,
			&i.Title,
			&i.WhatChanged,
			&i.WhoAffected,
			&i.Actions,
			&i.AudienceTags,
			&i.RegionCode,
			&i.Status,
			&i.PassedAt,
			&i.SignedAt,
			&i.EffectiveAt,
			&i.OfficialUrl,
			&i.SourceUrl,
			&i.ActNumber,
			&i.Quotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedLaws = `-- name: ListVerifiedLaws :many
SELECT
    id, title, what_changed, who_affected, actions, audience_tags, region_code, status,
    introduced_at, passed_at, signed_at, effective_at,
    official_url, bill_url, act_number, verified_at
FROM law_changes
WHERE verified
  AND (effective_at IS NULL OR (effective_at >= $1::date AND effective_at <= $2::date))
ORDER BY effective_at NULLS LAST, id
`

type ListVerifiedLawsParams struct {
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

type ListVerifiedLawsRow struct {
	ID           int64
	Title        string
	WhatChanged  string
	WhoAffected  string
	Actions      []byte
	AudienceTags []string
	RegionCode   pgtype.Text
	Status       string
	IntroducedAt pgtype.Date
	PassedAt     pgtype.Date
	SignedAt     pgtype.Date
	EffectiveAt  pgtype.Date
	OfficialUrl  pgtype.Text
	BillUrl      pgtype.Text
	ActNumber    pgtype.Text
	VerifiedAt   pgtype.Timestamptz
}

// Только проверенные вручную. Законы без даты вступления в силу (внесены/приняты) попадают всегда.
func (q *Queries) ListVerifiedLaws(ctx context.Context, arg ListVerifiedLawsParams) ([]ListVerifiedLawsRow, error) {
	rows, err := q.db.Query(ctx, listVerifiedLaws, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerifiedLawsRow
	for rows.Next() {
		var i ListVerifiedLawsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.WhatChanged,
			&i.WhoAffected,
			&i.Actions,
			&i.AudienceTags,
			&i.RegionCode,
			&i.Status,
			&i.IntroducedAt,
			&i.PassedAt,
			&i.SignedAt,
			&i.EffectiveAt,
			&i.OfficialUrl,
			&i.BillUrl,
			&i.ActNumber,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectLaw = `-- name: RejectLaw :exec
UPDATE law_changes SET rejected = true, reject_reason = $2 WHERE id = $1 AND NOT verified
`

type RejectLawParams struct {
	ID           int64
	RejectReason pgtype.Text
}

func (q *Queries) RejectLaw(ctx context.Context, arg RejectLawParams) error {
	_, err := q.db.Exec(ctx, rejectLaw, arg.ID, arg.RejectReason)
	return err
}

const updateLawDraft = `-- name: UpdateLawDraft :exec
UPDATE law_changes
SET title = $2, what_changed = $3, who_affected = $4, actions = $5, audience_tags = $6,
    region_code = $7, status = $8, effective_at = $9
WHERE id = $1 AND NOT verified
`

type UpdateLawDraftParams struct {
	ID           int64
	Title        string
	WhatChanged  string
	WhoAffected  string
	Actions      []byte
	AudienceTags []string
	RegionCode   pgtype.Text
	Status       string
	EffectiveAt  pgtype.Date
}

func (q *Queries) UpdateLawDraft(ctx context.Context, arg UpdateLawDraftParams) error {
	_, err := q.db.Exec(ctx, updateLawDraft,
		arg.ID,
		arg.Title,
		arg.WhatChanged,
		arg.WhoAffected,
		arg.Actions,
		arg.AudienceTags,
		arg.RegionCode,
		arg.Status,
		arg.EffectiveAt,
	)
	return err
}

const verifyLaw = `-- name: VerifyLaw :exec
UPDATE law_changes SET verified = true, verified_at = now() WHERE id = $1 AND NOT rejected
`

func (q *Queries) VerifyLaw(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, verifyLaw, id)
	return err
}
