// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LawChange struct {
	ID           int64
	Title        string
	WhatChanged  string
	WhoAffected  string
	Actions      []byte
	AudienceTags []string
	RegionCode   pgtype.Text
	Status       string
	IntroducedAt pgtype.Date
	PassedAt     pgtype.Date
	SignedAt     pgtype.Date
	EffectiveAt  pgtype.Date
	OfficialUrl  pgtype.Text
	BillUrl      pgtype.Text
	ActNumber    pgtype.Text
	Verified     bool
	VerifiedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type Post struct {
	ID          int64
	SourceID    int64
	ExternalID  string
	Url         string
	PublishedAt pgtype.Timestamptz
	Text        string
	Lang        string
	IsAd        bool
	Embedding   string
	StoryID     pgtype.Int8
	CreatedAt   pgtype.Timestamptz
	AdSuspected bool
}

type Source struct {
	ID                  int64
	Kind                string
	Handle              string
	Url                 string
	Title               string
	TopicHint           pgtype.Text
	LegalStatus         string
	Active              bool
	CreatedAt           pgtype.Timestamptz
	LegalCheckedAt      pgtype.Date
	LastFetchedAt       pgtype.Timestamptz
	LastError           pgtype.Text
	ConsecutiveFailures int32
}

type Story struct {
	ID                int64
	FirstSeenAt       pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Topic             pgtype.Text
	InfoType          pgtype.Text
	Heaviness         pgtype.Text
	TitleNeutral      pgtype.Text
	Summary           pgtype.Text
	Meaning           pgtype.Text
	PostCount         int32
	SourceCount       int32
	Centroid          string
	RegionCode        pgtype.Text
	Status            string
	LastPostAt        pgtype.Timestamptz
	DigestPostCount   int32
	DigestAttempts    int32
	DigestError       pgtype.Text
	DigestAt          pgtype.Timestamptz
	HasOfficialSource bool
}

type StoryPost struct {
	StoryID int64
	PostID  int64
}
