// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTokenUsage = `-- name: AddTokenUsage :exec
INSERT INTO llm_usage (day, prompt_tokens, completion_tokens) VALUES ($1::date, $2::bigint, $3::bigint)
ON CONFLICT (day) DO UPDATE SET prompt_tokens = llm_usage.prompt_tokens + EXCLUDED.prompt_tokens,
                                completion_tokens = llm_usage.completion_tokens + EXCLUDED.completion_tokens
`

type AddTokenUsageParams struct {
	Day        pgtype.Date
	Prompt     int64
	Completion int64
}

func (q *Queries) AddTokenUsage(ctx context.Context, arg AddTokenUsageParams) error {
	_, err := q.db.Exec(ctx, addTokenUsage, arg.Day, arg.Prompt, arg.Completion)
	return err
}

const attachPost = `-- name: AttachPost :exec
UPDATE posts SET story_id = $1 WHERE id = $2
`

type AttachPostParams struct {
	StoryID pgtype.Int8
	PostID  int64
}

func (q *Queries) AttachPost(ctx context.Context, arg AttachPostParams) error {
	_, err := q.db.Exec(ctx, attachPost, arg.StoryID, arg.PostID)
	return err
}

const attachStoryPost = `-- name: AttachStoryPost :exec
INSERT INTO story_posts (story_id, post_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AttachStoryPostParams struct {
	StoryID int64
	PostID  int64
}

func (q *Queries) AttachStoryPost(ctx context.Context, arg AttachStoryPostParams) error {
	_, err := q.db.Exec(ctx, attachStoryPost, arg.StoryID, arg.PostID)
	return err
}

const clearStoryDerived = `-- name: ClearStoryDerived :exec
UPDATE posts SET derived_from = NULL WHERE story_id = $1 AND derived_from IS NOT NULL
`

func (q *Queries) ClearStoryDerived(ctx context.Context, storyID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, clearStoryDerived, storyID)
	return err
}

const createStory = `-- name: CreateStory :one
INSERT INTO stories (first_seen_at, updated_at, last_post_at, post_count, source_count, has_official_source, status)
VALUES ($1, $2, $2, 0, 0, false, 'draft')
RETURNING id
`

type CreateStoryParams struct {
	FirstSeenAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateStory(ctx context.Context, arg CreateStoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, createStory, arg.FirstSeenAt, arg.UpdatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listOpenStoryPosts = `-- name: ListOpenStoryPosts :many
SELECT p.story_id, p.id, p.source_id, p.text, p.lang, p.published_at
FROM posts p
JOIN stories st ON st.id = p.story_id
WHERE st.status IN ('draft', 'published') AND st.first_seen_at > $1::timestamptz
ORDER BY p.story_id, p.published_at
`

type ListOpenStoryPostsRow struct {
	StoryID     pgtype.Int8
	ID          int64
	SourceID    int64
	Text        string
	Lang        string
	PublishedAt pgtype.Timestamptz
}

// Посты открытых сюжетов за окно склейки (для расчёта центров сюжетов).
func (q *Queries) ListOpenStoryPosts(ctx context.Context, since pgtype.Timestamptz) ([]ListOpenStoryPostsRow, error) {
	rows, err := q.db.Query(ctx, listOpenStoryPosts, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenStoryPostsRow
	for rows.Next() {
		var i ListOpenStoryPostsRow
		if err := rows.Scan(
			&i.StoryID,
			&i.ID,
			&i.SourceID,
			&i.Text,
			&i.Lang,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPosts = `-- name: ListRecentPosts :many
SELECT p.id, p.source_id, p.text, p.lang, p.published_at, p.story_id, src.title AS source_title, src.kind AS source_kind
FROM posts p JOIN sources src ON src.id = p.source_id
WHERE p.published_at > $1::timestamptz AND NOT p.is_ad
ORDER BY p.published_at, p.id
`

type ListRecentPostsRow struct {
	ID          int64
	SourceID    int64
	Text        string
	Lang        string
	PublishedAt pgtype.Timestamptz
	StoryID     pgtype.Int8
	SourceTitle string
	SourceKind  string
}

// Для отладки склейки: все нерекламные посты за окно вместе с текущим сюжетом.
func (q *Queries) ListRecentPosts(ctx context.Context, since pgtype.Timestamptz) ([]ListRecentPostsRow, error) {
	rows, err := q.db.Query(ctx, listRecentPosts, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentPostsRow
	for rows.Next() {
		var i ListRecentPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Text,
			&i.Lang,
			&i.PublishedAt,
			&i.StoryID,
			&i.SourceTitle,
			&i.SourceKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentStoryIDs = `-- name: ListRecentStoryIDs :many
SELECT id FROM stories WHERE status IN ('draft', 'published') AND first_seen_at > $1::timestamptz ORDER BY id
`

func (q *Queries) ListRecentStoryIDs(ctx context.Context, since pgtype.Timestamptz) ([]int64, error) {
	rows, err := q.db.Query(ctx, listRecentStoryIDs, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoriesForDigest = `-- name: ListStoriesForDigest :many
SELECT id, post_count, source_count, has_official_source, digest_attempts
FROM stories
WHERE status IN ('draft', 'published') AND post_count > 0
  AND last_post_at <= $1::timestamptz
  AND (title_neutral IS NULL OR post_count > digest_post_count)
  AND (source_count >= 2 OR has_official_source OR source_region IS NOT NULL)
  AND digest_attempts < $2::int
ORDER BY source_count DESC, last_post_at
LIMIT $3::int
`

type ListStoriesForDigestParams struct {
	QuietBefore pgtype.Timestamptz
	MaxAttempts int32
	Batch       int32
}

type ListStoriesForDigestRow struct {
	ID                int64
	PostCount         int32
	SourceCount       int32
	HasOfficialSource bool
	DigestAttempts    int32
}

// Сюжеты, которым пора делать пересказ: новых постов нет уже @quiet_for (дебаунс), попыток немного.
// Только те, что могут быть опубликованы (≥ 2 источников, официальный или региональный): остальные не стоит тратить токены.
// Сначала самые весомые (больше источников).
func (q *Queries) ListStoriesForDigest(ctx context.Context, arg ListStoriesForDigestParams) ([]ListStoriesForDigestRow, error) {
	rows, err := q.db.Query(ctx, listStoriesForDigest, arg.QuietBefore, arg.MaxAttempts, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStoriesForDigestRow
	for rows.Next() {
		var i ListStoriesForDigestRow
		if err := rows.Scan(
			&i.ID,
			&i.PostCount,
			&i.SourceCount,
			&i.HasOfficialSource,
			&i.DigestAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoryPostsForDigest = `-- name: ListStoryPostsForDigest :many
SELECT p.id, p.url, p.published_at, p.text, p.lang, src.title AS source_title, src.kind AS source_kind
FROM posts p JOIN sources src ON src.id = p.source_id
WHERE p.story_id = $1
ORDER BY p.published_at
LIMIT $2::int
`

type ListStoryPostsForDigestParams struct {
	StoryID pgtype.Int8
	Lim     int32
}

type ListStoryPostsForDigestRow struct {
	ID          int64
	Url         string
	PublishedAt pgtype.Timestamptz
	Text        string
	Lang        string
	SourceTitle string
	SourceKind  string
}

func (q *Queries) ListStoryPostsForDigest(ctx context.Context, arg ListStoryPostsForDigestParams) ([]ListStoryPostsForDigestRow, error) {
	rows, err := q.db.Query(ctx, listStoryPostsForDigest, arg.StoryID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStoryPostsForDigestRow
	for rows.Next() {
		var i ListStoryPostsForDigestRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.PublishedAt,
			&i.Text,
			&i.Lang,
			&i.SourceTitle,
			&i.SourceKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoryPostsForOriginality = `-- name: ListStoryPostsForOriginality :many
SELECT id, source_id, published_at, text FROM posts WHERE story_id = $1
`

type ListStoryPostsForOriginalityRow struct {
	ID          int64
	SourceID    int64
	PublishedAt pgtype.Timestamptz
	Text        string
}

func (q *Queries) ListStoryPostsForOriginality(ctx context.Context, storyID pgtype.Int8) ([]ListStoryPostsForOriginalityRow, error) {
	rows, err := q.db.Query(ctx, listStoryPostsForOriginality, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStoryPostsForOriginalityRow
	for rows.Next() {
		var i ListStoryPostsForOriginalityRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.PublishedAt,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnclusteredPosts = `-- name: ListUnclusteredPosts :many
SELECT p.id, p.source_id, p.url, p.published_at, p.text, p.lang, s.title AS source_title, s.kind AS source_kind
FROM posts p
JOIN sources s ON s.id = p.source_id
WHERE p.story_id IS NULL AND NOT p.is_ad AND p.published_at > $1::timestamptz
ORDER BY p.published_at, p.id
`

type ListUnclusteredPostsRow struct {
	ID          int64
	SourceID    int64
	Url         string
	PublishedAt pgtype.Timestamptz
	Text        string
	Lang        string
	SourceTitle string
	SourceKind  string
}

// Свежие нерекламные посты, ещё не отнесённые к сюжету.
func (q *Queries) ListUnclusteredPosts(ctx context.Context, since pgtype.Timestamptz) ([]ListUnclusteredPostsRow, error) {
	rows, err := q.db.Query(ctx, listUnclusteredPosts, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnclusteredPostsRow
	for rows.Next() {
		var i ListUnclusteredPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Url,
			&i.PublishedAt,
			&i.Text,
			&i.Lang,
			&i.SourceTitle,
			&i.SourceKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishReadyStories = `-- name: PublishReadyStories :execrows
UPDATE stories SET status = 'published'
WHERE status = 'draft' AND title_neutral IS NOT NULL AND (source_count >= 2 OR has_official_source OR source_region IS NOT NULL)
`

// Правило публикации (раздел 9): не меньше двух разных источников или официальный источник.
func (q *Queries) PublishReadyStories(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, publishReadyStories)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordDigestFailure = `-- name: RecordDigestFailure :exec
UPDATE stories SET digest_attempts = digest_attempts + 1, digest_error = $1::text WHERE id = $2
`

type RecordDigestFailureParams struct {
	Error string
	ID    int64
}

func (q *Queries) RecordDigestFailure(ctx context.Context, arg RecordDigestFailureParams) error {
	_, err := q.db.Exec(ctx, recordDigestFailure, arg.Error, arg.ID)
	return err
}

const recountStory = `-- name: RecountStory :exec
UPDATE stories s SET
    post_count = c.n,
    source_count = c.sources,
    has_official_source = c.official,
    last_post_at = c.last_at,
    country = c.country,
    source_region = c.region,
    lang = COALESCE(c.lang, s.lang),
    updated_at = GREATEST(s.updated_at, c.last_at)
FROM (
    SELECT count(*)::int AS n, (count(DISTINCT p.source_id) FILTER (WHERE p.derived_from IS NULL))::int AS sources,
           bool_or(src.kind = 'gov') AS official, max(p.published_at) AS last_at,
           mode() WITHIN GROUP (ORDER BY src.country) AS country,
           -- Регион сюжета — только если все его источники региональные и одного региона; иначе сюжет федеральный.
           CASE WHEN count(*) FILTER (WHERE src.region_code IS NULL) = 0 AND count(DISTINCT src.region_code) = 1
                THEN min(src.region_code) END AS region,
           mode() WITHIN GROUP (ORDER BY p.lang) AS lang
    FROM posts p JOIN sources src ON src.id = p.source_id
    WHERE p.story_id = $1
) c
WHERE s.id = $1
`

// Пересчёт счётчиков сюжета по его постам. Время обновления сдвигается только вперёд.
// source_count — число НЕЗАВИСИМЫХ источников: посты-пересказы (derived_from) не считаются.
func (q *Queries) RecountStory(ctx context.Context, storyID int64) error {
	_, err := q.db.Exec(ctx, recountStory, storyID)
	return err
}

const saveStoryDigest = `-- name: SaveStoryDigest :exec
UPDATE stories SET
    topic = $1, info_type = $2, heaviness = $3,
    title_neutral = $4, summary = $5, meaning = $6,
    region_code = $7,
    digest_post_count = post_count, digest_attempts = 0, digest_error = NULL, digest_at = $8::timestamptz,
    status = CASE WHEN NOT $9::boolean THEN 'skipped' WHEN status = 'skipped' THEN 'draft' ELSE status END
WHERE id = $10
`

type SaveStoryDigestParams struct {
	Topic      pgtype.Text
	InfoType   pgtype.Text
	Heaviness  pgtype.Text
	Title      pgtype.Text
	Summary    pgtype.Text
	Meaning    pgtype.Text
	RegionCode pgtype.Text
	At         pgtype.Timestamptz
	Newsworthy bool
	ID         int64
}

func (q *Queries) SaveStoryDigest(ctx context.Context, arg SaveStoryDigestParams) error {
	_, err := q.db.Exec(ctx, saveStoryDigest,
		arg.Topic,
		arg.InfoType,
		arg.Heaviness,
		arg.Title,
		arg.Summary,
		arg.Meaning,
		arg.RegionCode,
		arg.At,
		arg.Newsworthy,
		arg.ID,
	)
	return err
}

const setPostDerived = `-- name: SetPostDerived :exec
UPDATE posts SET derived_from = $1 WHERE id = $2
`

type SetPostDerivedParams struct {
	DerivedFrom pgtype.Int8
	PostID      int64
}

func (q *Queries) SetPostDerived(ctx context.Context, arg SetPostDerivedParams) error {
	_, err := q.db.Exec(ctx, setPostDerived, arg.DerivedFrom, arg.PostID)
	return err
}

const tokensUsedToday = `-- name: TokensUsedToday :one
SELECT COALESCE(sum(prompt_tokens + completion_tokens), 0)::bigint FROM llm_usage WHERE day = $1::date
`

func (q *Queries) TokensUsedToday(ctx context.Context, day pgtype.Date) (int64, error) {
	row := q.db.QueryRow(ctx, tokensUsedToday, day)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const unpublishWeakStories = `-- name: UnpublishWeakStories :execrows
UPDATE stories SET status = 'draft'
WHERE status = 'published' AND NOT (source_count >= 2 OR has_official_source OR source_region IS NOT NULL)
`

// Если сюжет перестал удовлетворять правилу (например, после ручной правки), возвращаем в черновики.
func (q *Queries) UnpublishWeakStories(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, unpublishWeakStories)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
