// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPost = `-- name: InsertPost :execrows
INSERT INTO posts (source_id, external_id, url, published_at, text, lang, is_ad, ad_suspected)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (source_id, external_id) DO NOTHING
`

type InsertPostParams struct {
	SourceID    int64
	ExternalID  string
	Url         string
	PublishedAt pgtype.Timestamptz
	Text        string
	Lang        string
	IsAd        bool
	AdSuspected bool
}

// Дубликаты по (source_id, external_id) молча пропускаются.
func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPost,
		arg.SourceID,
		arg.ExternalID,
		arg.Url,
		arg.PublishedAt,
		arg.Text,
		arg.Lang,
		arg.IsAd,
		arg.AdSuspected,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveSources = `-- name: ListActiveSources :many
SELECT id, kind, handle, url, title, topic_hint, country, lang, last_fetched_at, consecutive_failures
FROM sources
WHERE active AND legal_status = 'ok' AND legal_checked_at IS NOT NULL
ORDER BY id
`

type ListActiveSourcesRow struct {
	ID                  int64
	Kind                string
	Handle              string
	Url                 string
	Title               string
	TopicHint           pgtype.Text
	Country             pgtype.Text
	Lang                string
	LastFetchedAt       pgtype.Timestamptz
	ConsecutiveFailures int32
}

func (q *Queries) ListActiveSources(ctx context.Context) ([]ListActiveSourcesRow, error) {
	rows, err := q.db.Query(ctx, listActiveSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSourcesRow
	for rows.Next() {
		var i ListActiveSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Handle,
			&i.Url,
			&i.Title,
			&i.TopicHint,
			&i.Country,
			&i.Lang,
			&i.LastFetchedAt,
			&i.ConsecutiveFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordFetchFailure = `-- name: RecordFetchFailure :exec
UPDATE sources
SET last_fetched_at = $1::timestamptz, last_error = $2::text, consecutive_failures = consecutive_failures + 1
WHERE id = $3
`

type RecordFetchFailureParams struct {
	FetchedAt pgtype.Timestamptz
	Error     string
	ID        int64
}

func (q *Queries) RecordFetchFailure(ctx context.Context, arg RecordFetchFailureParams) error {
	_, err := q.db.Exec(ctx, recordFetchFailure, arg.FetchedAt, arg.Error, arg.ID)
	return err
}

const recordFetchSuccess = `-- name: RecordFetchSuccess :exec
UPDATE sources
SET last_fetched_at = $1::timestamptz, last_error = NULL, consecutive_failures = 0
WHERE id = $2
`

type RecordFetchSuccessParams struct {
	FetchedAt pgtype.Timestamptz
	ID        int64
}

func (q *Queries) RecordFetchSuccess(ctx context.Context, arg RecordFetchSuccessParams) error {
	_, err := q.db.Exec(ctx, recordFetchSuccess, arg.FetchedAt, arg.ID)
	return err
}

const upsertSource = `-- name: UpsertSource :exec
INSERT INTO sources (kind, handle, url, title, topic_hint, country, region_code, lang, legal_status, legal_checked_at, active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10::date, $11)
ON CONFLICT (kind, handle) DO UPDATE SET
    url = EXCLUDED.url,
    title = EXCLUDED.title,
    topic_hint = EXCLUDED.topic_hint,
    country = EXCLUDED.country,
    region_code = EXCLUDED.region_code,
    lang = EXCLUDED.lang,
    legal_status = EXCLUDED.legal_status,
    legal_checked_at = EXCLUDED.legal_checked_at,
    active = EXCLUDED.active
`

type UpsertSourceParams struct {
	Kind           string
	Handle         string
	Url            string
	Title          string
	TopicHint      pgtype.Text
	Country        pgtype.Text
	RegionCode     pgtype.Text
	Lang           string
	LegalStatus    string
	LegalCheckedAt pgtype.Date
	Active         bool
}

// Каталог из seeds/sources.yaml. Активность ограничена CHECK-ограничением (нужна дата проверки по реестрам).
func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) error {
	_, err := q.db.Exec(ctx, upsertSource,
		arg.Kind,
		arg.Handle,
		arg.Url,
		arg.Title,
		arg.TopicHint,
		arg.Country,
		arg.RegionCode,
		arg.Lang,
		arg.LegalStatus,
		arg.LegalCheckedAt,
		arg.Active,
	)
	return err
}
